[project]
name = "statement-analyser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Palash Jain", email = "palash.jain.cw@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.1.0",
    "pydantic-settings>=2.12.0",
    "python-dotenv>=1.2.1",
    "ruff>=0.14.10",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
